---
- name: Deploy k3s agent config
  template:
    src: k3s-agent.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: "0600"

- name: Install k3s agent
  shell: curl -sfL https://get.k3s.io | sh -s - agent
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    K3S_TOKEN: "{{ k3s_token }}"
    K3S_URL: "https://{{ init_master_ip }}:6443"
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s-agent service to become active
  command: systemctl is-active k3s-agent
  register: k3s_agent_active
  until: k3s_agent_active.stdout == "active"
  retries: 30
  delay: 10
  changed_when: false
