---
- name: Wait for API server to be ready
  kubernetes.core.k8s_info:
    kind: Node
  register: nodes
  until: nodes.resources is defined and nodes.resources | length > 0
  retries: 30
  delay: 10
  failed_when: false
  delegate_to: localhost
  become: false

- import_tasks: cert_manager.yml
- import_tasks: metallb.yml
- import_tasks: traefik.yml
- import_tasks: argocd.yml
