---
- name: Deploy cluster addons
  hosts: k3s_init_master
  become: false
  gather_facts: false
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/k3s-config"
    kubernetes.core.k8s_info:
      kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/k3s-config"
  roles:
    - addons
